In [ ]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as mse
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression

In [129]:
file_path='./Assessor_Historical_Secured_Property_Tax_Rolls.csv'
data=pd.read_csv(file_path)
data#.head()

/srv/app/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (11,12,13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Closed Roll Year,Property Location,Parcel Number,Block,Lot,Volume Number,Use Code,Use Definition,Property Class Code,Property Class Code Definition,...,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods,DELETE - Supervisor Districts,DELETE - Fire Prevention Districts,DELETE - Current Police Districts,DELETE - Zip Codes,DELETE - Neighborhoods,DELETE - Police Districts
0,2007,0000 0000 0000,1378007,1378,007,10,MISC,Miscellaneous/Mixed-Use,V,Vacant Lot,...,2.0,8.0,4.0,29.0,2.0,11.0,9.0,55,26.0,6.0
1,2008,0000 0000 0000,1345001,1345,001,10,MISC,Miscellaneous/Mixed-Use,V,Vacant Lot,...,4.0,NaN,6.0,11.0,1.0,11.0,NaN,54,11.0,NaN
2,2008,0000 0000 0000,5607046,5607,046,33,MISC,Miscellaneous/Mixed-Use,V,Vacant Lot,...,83.0,9.0,2.0,25.0,7.0,10.0,4.0,"28,859",28.0,7.0
3,2009,0000 0297 BALTIMORE WY0000,6499040,6499,040,38,SRES,Single Family Residential,D,Dwelling,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"28,588",NaN,NaN
4,2010,0000 1715 SITUS TO BE ASSIGNEDST0000,0663054,0663,054,5,COMM,Commercial Misc,E,Schools,...,101.0,4.0,11.0,30.0,11.0,13.0,6.0,"28,858",27.0,9.0
5,2010,0000 0000 0000,4046002,4046,002,27,IND,Industrial,I,Industrial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,310,NaN,NaN
6,2010,0000 0000VDONNER AV0000,4894005,4894,005,30,MISC,Miscellaneous/Mixed-Use,V,Vacant Lot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,NaN,NaN
7,2010,0000 0000 0000,6472077,6472,077,38,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"28,588",NaN,NaN
8,2007,0000 0666 POST ST1503,0298C050,0298C,050,3,SRES,Single Family Residential,COS,Coop Units Segregated,...,50.0,6.0,3.0,21.0,10.0,5.0,1.0,"28,852",21.0,1.0
9,2007,0000 0650 CHESTNUT ST0202,0051091,0051,091,1,SRES,Single Family Residential,Z,Condominium,...,106.0,6.0,3.0,23.0,10.0,3.0,1.0,308,23.0,1.0
10,2007,0000 0611 WASHINGTON ST2402,0208051,0208,051,2,SRES,Single Family Residential,Z,Condominium,...,104.0,6.0,3.0,6.0,10.0,3.0,1.0,"28,860",4.0,1.0
11,2007,0000 2655 HYDE ST0105,0026T245B,0026T,245B,1,COMM,Commercial Misc,TS,Timeshare,...,98.0,6.0,6.0,32.0,1.0,5.0,1.0,"28,858",32.0,1.0
12,2007,0000 0201 GRANT AV0000,0294006,0294,006,3,COMO,Commercial Office,O,Office,...,19.0,6.0,3.0,8.0,10.0,5.0,1.0,"28,857",6.0,1.0
13,2007,0000 2655 HYDE ST0103,0026T383A,0026T,383A,1,COMM,Commercial Misc,TS,Timeshare,...,98.0,6.0,6.0,32.0,1.0,5.0,1.0,"28,858",32.0,1.0
14,2007,0000 0000 0000,0024032,0024,032,1,SRES,Single Family Residential,Z,Condominium,...,99.0,6.0,6.0,32.0,1.0,5.0,1.0,"28,858",32.0,1.0
15,2007,0000 1000 PINE ST0019N,0253T019N,0253T,019N,3,COMM,Commercial Misc,TS,Timeshare,...,16.0,6.0,3.0,21.0,10.0,5.0,1.0,"28,857",21.0,1.0
16,2007,0730 0726 GREEN ST0000,0118011,0118,011,1,MRES,Multi-Family Residential,A,Apartment,...,107.0,6.0,3.0,6.0,10.0,3.0,1.0,308,4.0,1.0
17,2007,0000 1825 LEAVENWORTH ST0000,0125005,0125,005,2,MRES,Multi-Family Residential,A,Apartment,...,107.0,6.0,3.0,32.0,10.0,5.0,1.0,"28,858",32.0,1.0
18,2007,1326 1324 POWELL ST0000,0160014A,0160,014A,2,COMR,Commercial Retail,C,Commercial Stores,...,104.0,6.0,3.0,6.0,10.0,3.0,1.0,308,4.0,1.0
19,2007,0000 1925 LEAVENWORTH ST0012,0122047,0122,047,1,SRES,Single Family Residential,Z,Condominium,...,107.0,6.0,3.0,32.0,10.0,5.0,1.0,"28,858",32.0,1.0
20,2007,0000 0441 MASON ST0000,0306T161A,0306T,161A,3,COMM,Commercial Misc,TS,Timeshare,...,50.0,6.0,3.0,36.0,10.0,5.0,1.0,"28,852",36.0,1.0
21,2007,0000 0875 SACRAMENTO ST0000,0242030,0242,030,3,MRES,Multi-Family Residential,A,Apartment,...,104.0,6.0,3.0,6.0,10.0,3.0,1.0,"28,857",4.0,1.0
22,2007,0000 0849 MASON ST0001,0254092,0254,092,3,SRES,Single Family Residential,Z,Condominium,...,16.0,6.0,3.0,21.0,10.0,5.0,1.0,"28,857",21.0,1.0
23,2007,0000 0485 PINE ST0000,0269020,0269,020,3,COMR,Commercial Retail,C,Commercial Stores,...,108.0,6.0,3.0,8.0,10.0,4.0,1.0,"28,854",6.0,1.0
24,2007,0000 0690 CHESTNUT ST0202C,0051127,0051,127,1,SRES,Single Family Residential,Z,Condominium,...,106.0,6.0,3.0,23.0,10.0,3.0,1.0,308,23.0,1.0
25,2007,1538 1534 JONES ST0000,0182020,0182,020,2,MRES,Multi-Family Residential,F,Flats & Duplex,...,16.0,6.0,3.0,21.0,10.0,5.0,1.0,308,21.0,1.0
26,2007,0377 0367 CHESTNUT ST0000,0062023,0062,023,1,MRES,Multi-Family Residential,A,Apartment,...,106.0,6.0,3.0,23.0,10.0,3.0,1.0,308,23.0,1.0
27,2007,0000 0620 SUTTER ST0000,0283004A,0283,004A,3,COMH,Commercial Hotel,H2,Hotels - Other,...,50.0,6.0,3.0,21.0,10.0,5.0,1.0,"28,857",21.0,1.0
28,2007,0000 0700 MONTGOMERY ST0000,0196028,0196,028,2,COMO,Commercial Office,O,Office,...,106.0,6.0,3.0,6.0,10.0,3.0,1.0,"28,860",4.0,1.0
29,2007,0820 0818 GREEN ST0000,0119011,0119,011,1,MRES,Multi-Family Residential,F,Flats & Duplex,...,107.0,6.0,3.0,32.0,10.0,3.0,1.0,308,32.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130183,2007,0571 0569 ELIZABETH ST0000,3656030,3656,030,24,MRES,Multi-Family Residential,F,Flats & Duplex,...,84.0,3.0,5.0,22.0,5.0,2.0,7.0,"28,862",22.0,4.0
130184,2007,0000 0516 NATOMA ST0000,3726057,3726,057,25,MRES,Multi-Family Residential,F,Flats & Duplex,...,32.0,1.0,10.0,34.0,9.0,14.0,2.0,"28,853",34.0,2.0
130185,2007,0000 0532 WISCONSIN ST0000,4070018,4070,018,27,SRES,Single Family Residential,Z,Condominium,...,54.0,2.0,9.0,26.0,8.0,10.0,3.0,"28,856",29.0,3.0
130186,2007,0000 0855 FOLSOM ST0504,3752269,3752,269,25,SRES,Single Family Residential,Z,Condominium,...,32.0,1.0,10.0,34.0,9.0,6.0,2.0,"28,856",34.0,2.0
130187,2007,0000 0602 THE EMBARCADERO 0000,3791001,3791,001,25,MISC,Miscellaneous/Mixed-Use,X,Misc,...,31.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,856",6.0,2.0
130188,2007,0000 0600 PENNSYLVANIA AV0000,4103016,4103,016,27,SRES,Single Family Residential,D,Dwelling,...,54.0,2.0,9.0,26.0,8.0,10.0,3.0,"28,856",29.0,3.0
130189,2007,0000 0000 0000,3747134,3747,134,25,SRES,Single Family Residential,Z,Condominium,...,30.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,855",6.0,2.0
130190,2007,0000 0584 ALABAMA ST0000,4019010,4019,010,26,SRES,Single Family Residential,Z,Condominium,...,53.0,3.0,2.0,20.0,7.0,8.0,7.0,"28,859",19.0,4.0
130191,2007,0000 2103 18TH ST0000,4029024,4029,024,26,MISC,Miscellaneous/Mixed-Use,V,Vacant Lot,...,54.0,2.0,9.0,26.0,8.0,10.0,3.0,"28,856",29.0,3.0
130192,2007,0000 0333 01ST STN906,3748099,3748,099,25,SRES,Single Family Residential,Z,Condominium,...,30.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,855",6.0,2.0
130193,2007,0000 0555 04TH ST0932,3776451,3776,451,25,SRES,Single Family Residential,LZ,Live/Work Condominium,...,32.0,1.0,10.0,34.0,9.0,6.0,2.0,"28,856",34.0,2.0
130194,2007,0000 0069 CLEMENTINA ST0601,3736171,3736,171,25,SRES,Single Family Residential,Z,Condominium,...,32.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,855",6.0,2.0
130195,2007,0000 0355 BRYANT ST0109,3774083,3774,083,25,SRES,Single Family Residential,LZ,Live/Work Condominium,...,31.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,856",6.0,2.0
130196,2007,0301 0000 FOLSOM ST0307,3747036,3747,036,25,SRES,Single Family Residential,LZ,Live/Work Condominium,...,30.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,855",6.0,2.0
130197,2007,0000 0580 HOWARD ST0204,3721097,3721,097,25,SRES,Single Family Residential,LZ,Live/Work Condominium,...,32.0,1.0,10.0,8.0,9.0,12.0,2.0,"28,855",6.0,2.0
130198,2007,0000 0201 HARRISON ST0900,3767249,3767,249,25,SRES,Single Family Residential,Z,Condominium,...,30.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,855",6.0,2.0
130199,2007,0000 0088 TOWNSEND ST0215,3789905,3789,905,25,SRES,Single Family Residential,Z,Condominium,...,31.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,856",6.0,2.0
130200,2007,0000 0425 1ST ST3306,3765230,3765,230,25,SRES,Single Family Residential,Z,Condominium,...,30.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,855",6.0,2.0
130201,2007,0000 0200 BRANNAN ST0241,3774328,3774,328,25,SRES,Single Family Residential,Z,Condominium,...,31.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,856",6.0,2.0
130202,2007,0000 0485 IRWIN ST0000,3821006,3821,006,25,MISC,Miscellaneous/Mixed-Use,X,Misc,...,33.0,1.0,9.0,4.0,8.0,14.0,3.0,"28,856",20.0,3.0
130203,2007,0000 0425 1ST ST2105,3765145,3765,145,25,SRES,Single Family Residential,Z,Condominium,...,30.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,855",6.0,2.0
130204,2007,0882 0878 POTRERO AV0000,4089016,4089,016,27,MRES,Multi-Family Residential,F,Flats & Duplex,...,53.0,3.0,2.0,20.0,7.0,10.0,7.0,"28,859",19.0,4.0
130205,2007,0000 0765 MARKET ST0PH2A,3706255,3706,255,25,SRES,Single Family Residential,Z,Condominium,...,32.0,5.0,10.0,8.0,9.0,12.0,2.0,"28,853",6.0,2.0
130206,2007,0000 0855 FOLSOM ST0906,3752355,3752,355,25,SRES,Single Family Residential,Z,Condominium,...,32.0,1.0,10.0,34.0,9.0,6.0,2.0,"28,856",34.0,2.0
130207,2007,0000 0009 SCOTT AL0000,3752138,3752,138,25,SRES,Single Family Residential,Z,Condominium,...,32.0,1.0,10.0,34.0,9.0,6.0,2.0,"28,856",34.0,2.0
130208,2007,0000 0188 MINNA ST0033F,3722330,3722,330,25,SRES,Single Family Residential,Z,Condominium,...,32.0,1.0,10.0,8.0,9.0,12.0,2.0,"28,855",6.0,2.0
130209,2007,0000 0555 04TH ST0713,3776334,3776,334,25,SRES,Single Family Residential,LZ,Live/Work Condominium,...,32.0,1.0,10.0,34.0,9.0,6.0,2.0,"28,856",34.0,2.0
130210,2007,0000 0650 DELANCEY ST0104,3789447,3789,447,25,SRES,Single Family Residential,LZ,Live/Work Condominium,...,31.0,1.0,10.0,8.0,9.0,6.0,2.0,"28,856",6.0,2.0
130211,2007,0000 1001 HARRISON ST0000,3759002,3759,002,25,COMR,Commercial Retail,C,Commercial Stores,...,32.0,1.0,10.0,34.0,9.0,14.0,2.0,"28,853",34.0,2.0
130212,2007,0000 0340 06TH ST0304,3754077,3754,077,25,SRES,Single Family Residential,LZ,Live/Work Condominium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
cols = list(data.columns)#, list(data.index)
cols#, indices[:10]
#len(cols) == 53
#0
#5 volume number
#6 Use Code
#8 Property Class Code
#10 year built
#[11-15] number of br, bedr, room, stories, units
#17 const type
#[18-22] Lot areas (depth, frontage, prop area, basement area, lot area)
#[32-35] Values

['Closed Roll Year',
 'Property Location',
 'Parcel Number',
 'Block',
 'Lot',
 'Volume Number',
 'Use Code',
 'Use Definition',
 'Property Class Code',
 'Property Class Code Definition',
 'Year Property Built',
 'Number of Bathrooms',
 'Number of Bedrooms',
 'Number of Rooms',
 'Number of Stories',
 'Number of Units',
 'Zoning Code',
 'Construction Type',
 'Lot Depth',
 'Lot Frontage',
 'Property Area',
 'Basement Area',
 'Lot Area',
 'Lot Code',
 'Tax Rate Area Code',
 'Percent of Ownership',
 'Exemption Code',
 'Exemption Code Definition',
 'Status Code',
 'Misc Exemption Value',
 'Homeowner Exemption Value',
 'Current Sales Date',
 'Assessed Fixtures Value',
 'Assessed Improvement Value',
 'Assessed Land Value',
 'Assessed Personal Property Value',
 'Assessor Neighborhood District',
 'Assessor Neighborhood Code',
 'Assessor Neighborhood',
 'Supervisor District',
 'Analysis Neighborhood',
 'the_geom',
 'Row ID',
 'SF Find Neighborhoods',
 'Current Police Districts',
 'Current Supervisor Districts',
 'Analysis Neighborhoods',
 'DELETE - Supervisor Districts',
 'DELETE - Fire Prevention Districts',
 'DELETE - Current Police Districts',
 'DELETE - Zip Codes',
 'DELETE - Neighborhoods',
 'DELETE - Police Districts']

In [131]:
##Delete irrelevant end features
data = data.iloc[:, :-6]
#data.head()

In [132]:
sub = data.iloc[:, [0,5,6,8,10,11,12,13,14,15,17,18,19,20,21,22,32,33,34,35]]
sub.head()

,Closed Roll Year,Volume Number,Use Code,Property Class Code,Year Property Built,Number of Bathrooms,Number of Bedrooms,Number of Rooms,Number of Stories,Number of Units,Construction Type,Lot Depth,Lot Frontage,Property Area,Basement Area,Lot Area,Assessed Fixtures Value,Assessed Improvement Value,Assessed Land Value,Assessed Personal Property Value
0,2007,10,MISC,V,NaN,0,0,0,0,0,NaN,0.0,0.0,0,0,"35,997",0,0,0,0
1,2008,10,MISC,V,NaN,0,0,0,0,0,NaN,0.0,0.0,0,0,"653,400",0,0,0,0
2,2008,33,MISC,V,NaN,0,0,0,0,0,NaN,0.0,0.0,0,0,"43,925",0,0,0,0
3,2009,38,SRES,D,NaN,2,0,6,1,1,D,0.0,0.0,"1,238",0,"5,214",0,"45,734","22,044",0
4,2010,5,COMM,E,NaN,0,0,0,0,0,NaN,0.0,0.0,0,0,0,0,0,0,0

In [133]:
#SINGLE RESIDENTIAL. UNINTERESTED IN COMMERCIAL, GOVT, ETC. THIS HELPS REDUCE LENGTH OF DATASET

In [134]:
sub = sub[sub["Use Code"] == "SRES"]

In [135]:
years = list(set(sub["Closed Roll Year"].values))
useCode = list(set(sub["Use Code"].values))
classCode = list(set(sub["Property Class Code"].values))

In [136]:
newS = []
sub["Assessed Improvement Value"] = sub["Assessed Improvement Value"].fillna(0)
for i in sub["Assessed Improvement Value"].values:
    if type(i) == float:
        i = math.floor(i)
        newS += [i]
    if type(i) == str:
        newS += [int(i.replace(',', ''))]
    else:
        newS += [i]
#newS

In [137]:
sub["Assessed Improvement Value"] = newS

In [138]:
##Fixtures

In [139]:
newS1 = []
sub["Assessed Fixtures Value"] = sub["Assessed Fixtures Value"].fillna(0)
for i in sub["Assessed Fixtures Value"].values:
    if type(i) == float:
        i = math.floor(i)
        newS1 += [i]
    if type(i) == str:
        newS1 += [int(i.replace(',', ''))]
    else:
        newS1 += [i]
#newS1

In [140]:
sub["Assessed Fixtures Value"] = newS1

In [141]:
##Land Value

In [142]:
newS2 = []
sub["Assessed Land Value"] = sub["Assessed Land Value"].fillna(0)
for i in sub["Assessed Land Value"].values:
    if type(i) == float:
        i = math.floor(i)
        newS2 += [i]
    if type(i) == str:
        newS2 += [int(i.replace(',', ''))]
    else:
        newS2 += [i]
#newS2

In [143]:
sub["Assessed Land Value"] = newS2

In [144]:
sub.head()

,Closed Roll Year,Volume Number,Use Code,Property Class Code,Year Property Built,Number of Bathrooms,Number of Bedrooms,Number of Rooms,Number of Stories,Number of Units,Construction Type,Lot Depth,Lot Frontage,Property Area,Basement Area,Lot Area,Assessed Fixtures Value,Assessed Improvement Value,Assessed Land Value,Assessed Personal Property Value
3,2009,38,SRES,D,NaN,2,0,6,1,1,D,0.0,0.0,"1,238",0,"5,214",0,45734,22044,0
8,2007,3,SRES,COS,NaN,0,0,0,0,0,NaN,0.0,0.0,0,0,0,0,143223,35803,0
9,2007,1,SRES,Z,NaN,2,3,0,0,1,D,0.0,0.0,"1,334",0,0,0,284690,122009,0
10,2007,2,SRES,Z,NaN,3,3,6,1,1,C,0.0,0.0,"2,624",0,0,0,1717469,1717469,0
14,2007,1,SRES,Z,NaN,0,0,0,0,1,NaN,0.0,0.0,"1,482",0,0,0,479646,441055,0

In [145]:
sub["Value"] = sub["Assessed Fixtures Value"] + sub["Assessed Improvement Value"] + sub["Assessed Land Value"]

In [146]:
sub.head()

,Closed Roll Year,Volume Number,Use Code,Property Class Code,Year Property Built,Number of Bathrooms,Number of Bedrooms,Number of Rooms,Number of Stories,Number of Units,...,Lot Depth,Lot Frontage,Property Area,Basement Area,Lot Area,Assessed Fixtures Value,Assessed Improvement Value,Assessed Land Value,Assessed Personal Property Value,Value
3,2009,38,SRES,D,NaN,2,0,6,1,1,...,0.0,0.0,"1,238",0,"5,214",0,45734,22044,0,67778
8,2007,3,SRES,COS,NaN,0,0,0,0,0,...,0.0,0.0,0,0,0,0,143223,35803,0,179026
9,2007,1,SRES,Z,NaN,2,3,0,0,1,...,0.0,0.0,"1,334",0,0,0,284690,122009,0,406699
10,2007,2,SRES,Z,NaN,3,3,6,1,1,...,0.0,0.0,"2,624",0,0,0,1717469,1717469,0,3434938
14,2007,1,SRES,Z,NaN,0,0,0,0,1,...,0.0,0.0,"1,482",0,0,0,479646,441055,0,920701

In [147]:
subCols = list(sub.columns)
subCols

['Closed Roll Year',
 'Volume Number',
 'Use Code',
 'Property Class Code',
 'Year Property Built',
 'Number of Bathrooms',
 'Number of Bedrooms',
 'Number of Rooms',
 'Number of Stories',
 'Number of Units',
 'Construction Type',
 'Lot Depth',
 'Lot Frontage',
 'Property Area',
 'Basement Area',
 'Lot Area',
 'Assessed Fixtures Value',
 'Assessed Improvement Value',
 'Assessed Land Value',
 'Assessed Personal Property Value',
 'Value']

In [148]:
#set(sub["Value"].values)

In [149]:
##FEATURE SELECTION

In [150]:
sub.head()

,Closed Roll Year,Volume Number,Use Code,Property Class Code,Year Property Built,Number of Bathrooms,Number of Bedrooms,Number of Rooms,Number of Stories,Number of Units,...,Lot Depth,Lot Frontage,Property Area,Basement Area,Lot Area,Assessed Fixtures Value,Assessed Improvement Value,Assessed Land Value,Assessed Personal Property Value,Value
3,2009,38,SRES,D,NaN,2,0,6,1,1,...,0.0,0.0,"1,238",0,"5,214",0,45734,22044,0,67778
8,2007,3,SRES,COS,NaN,0,0,0,0,0,...,0.0,0.0,0,0,0,0,143223,35803,0,179026
9,2007,1,SRES,Z,NaN,2,3,0,0,1,...,0.0,0.0,"1,334",0,0,0,284690,122009,0,406699
10,2007,2,SRES,Z,NaN,3,3,6,1,1,...,0.0,0.0,"2,624",0,0,0,1717469,1717469,0,3434938
14,2007,1,SRES,Z,NaN,0,0,0,0,1,...,0.0,0.0,"1,482",0,0,0,479646,441055,0,920701

In [151]:
## 5-8] number rooms
##11-15 areas

In [152]:
X = sub.iloc[:,[5,6,7,8,11,12,13,14,15]]
X.head()

,Number of Bathrooms,Number of Bedrooms,Number of Rooms,Number of Stories,Lot Depth,Lot Frontage,Property Area,Basement Area,Lot Area
3,2,0,6,1,0.0,0.0,"1,238",0,"5,214"
8,0,0,0,0,0.0,0.0,0,0,0
9,2,3,0,0,0.0,0.0,"1,334",0,0
10,3,3,6,1,0.0,0.0,"2,624",0,0
14,0,0,0,0,0.0,0.0,"1,482",0,0

In [153]:
xCols = list(X.columns)
xCols

['Number of Bathrooms',
 'Number of Bedrooms',
 'Number of Rooms',
 'Number of Stories',
 'Lot Depth',
 'Lot Frontage',
 'Property Area',
 'Basement Area',
 'Lot Area']

In [154]:
for i in xCols:
    X[i] = X[i].fillna(0)
    newSeries = []
    for j in X[i].values:
        if type(j) == float:
            j = math.floor(j)
            newSeries += [j]
        elif type(j) == str:
            newSeries += [int(j.replace(',', '').replace('.',''))]
        else:
            newSeries += [j]
    X[i] = newSeries

/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [155]:
[type(X[i][3]) for i in X.columns]

[numpy.int64,
 numpy.int64,
 numpy.int64,
 numpy.int64,
 numpy.float64,
 numpy.float64,
 numpy.int64,
 numpy.int64,
 numpy.int64]

In [156]:
X.head()

,Number of Bathrooms,Number of Bedrooms,Number of Rooms,Number of Stories,Lot Depth,Lot Frontage,Property Area,Basement Area,Lot Area
3,2,0,6,1,0.0,0.0,1238,0,5214
8,0,0,0,0,0.0,0.0,0,0,0
9,2,3,0,0,0.0,0.0,1334,0,0
10,3,3,6,1,0.0,0.0,2624,0,0
14,0,0,0,0,0.0,0.0,1482,0,0

In [157]:
#X = sub.iloc[:,[13]]
#X.head()

In [158]:
Y = sub["Value"]
#Y

In [169]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = .2, random_state = 100)
print ('Number of samples in training data:',len(x_train))
print ('Number of samples in validation data:',len(x_test))

Number of samples in training data: 65741
Number of samples in validation data: 16436

In [170]:
model = linear_model.LinearRegression().fit(x_train, y_train)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [171]:
y_train_pred = model.predict(x_train)
training_error = mse(y_train, y_train_pred)
#(1 - linearReg_model.score(x_train, y_train)) * 100
print("Training Error (Mean squared error) :",training_error)

y_test_pred = model.predict(x_test)
test_error= mse(y_test, y_test_pred)
#(1 - linearReg_model.score(x_test, y_test)) * 100
print("Test Error (Mean squared error) :",test_error)

Training Error (Mean squared error) : 325378529800.3672
Test Error (Mean squared error) : 354733184030.668

In [110]:
#X.loc[14,:]

0.0

In [111]:
#model.predict(X.iloc[[14,15],:].values)

array([409564.57397731, 412522.69767201])

In [162]:
#Y

In [6]:
#ActualFrame=pd.DataFrame(data.iloc[:,31:36])
#ActualFrame=ActualFrame.dropna()
# Sum the 4 value columns and then do a regression of the sum of the assessed vales against the current sales date
# Use this linear regression to predict the cost of the current home in the future

,Current Sales Date,Assessed Fixtures Value,Assessed Improvement Value,Assessed Land Value,Assessed Personal Property Value
9,1996/06/27,0,284690,122009,0
10,2002/11/08,0,1717469,1717469,0
14,2001/07/24,0,479646,441055,0
15,2000/04/20,0,2250,2250,0
19,1989/08/21,0,119460,96117,0
...,...,...,...,...,...
2029407,1969/02/28,0,0,0,0
2029409,1969/02/28,0,0,0,0
2029410,1969/02/28,0,0,0,0
2029418,1993/08/01,0,0,0,0
2029420,1995/05/15,0,0,0,0