In [1]:
import pandas as pd

# SF Housing Data #

In [2]:
median_prices = pd.read_csv('SF_Redfin_RealEstate_Refined.csv')

In [3]:
median_prices.head()

,Month of Period End,Region,Avg. Median Sale Price,Avg. Median Ppsf
0,Feb-12,"San Francisco, CA - Western South of Market",$522K,514.7540984
1,Mar-12,"San Francisco, CA - Western South of Market",$519K,496.0554931
2,Apr-12,"San Francisco, CA - Western South of Market",$530K,508.4507042
3,May-12,"San Francisco, CA - Western South of Market",$540K,530.2325581
4,Jun-12,"San Francisco, CA - Western South of Market",$590K,532.2981146

In [4]:
median_prices.Region.unique()

array(['San Francisco, CA - Western South of Market',
       'San Francisco, CA - Western Addition',
       'San Francisco, CA - West Portal',
       'San Francisco, CA - Visitacion Valley',
       'San Francisco, CA - Upper Market',
       'San Francisco, CA - University Mound',
       'San Francisco, CA - Union Street',
       'San Francisco, CA - Tenderloin',
       'San Francisco, CA - Telegraph Hill',
       'San Francisco, CA - Sutro Heights',
       'San Francisco, CA - Sunnyside',
       'San Francisco, CA - St. Marys Park',
       'San Francisco, CA - Southwest San Francisco',
       'San Francisco, CA - Southeast San Francisco',
       'San Francisco, CA - South of Market',
       'San Francisco, CA - South Beach',
       'San Francisco, CA - Silver Terrace',
       'San Francisco, CA - Russian Hill',
       'San Francisco, CA - Rincon Hill',
       'San Francisco, CA - Presidio Terrace',
       'San Francisco, CA - Presidio Heights',
       'San Francisco, CA - Potrero Hill', 'San Francisco, CA - Portola',
       'San Francisco, CA - Polk Gulch',
       'San Francisco, CA - Peralta Heights',
       'San Francisco, CA - Parkside', 'San Francisco, CA - Panhandle',
       'San Francisco, CA - Pacific Heights',
       'San Francisco, CA - Outer Sunset',
       'San Francisco, CA - Outer Richmond',
       'San Francisco, CA - Outer Mission',
       'San Francisco, CA - Oceanview',
       'San Francisco, CA - Northwest San Francisco',
       'San Francisco, CA - Northeast San Francisco',
       'San Francisco, CA - North Beach',
       'San Francisco, CA - Noe Valley', 'San Francisco, CA - Nob Hill',
       'San Francisco, CA - Mission Terrace',
       'San Francisco, CA - Mission Dolores',
       'San Francisco, CA - Mission District',
       'San Francisco, CA - Mission Bay',
       'San Francisco, CA - Miraloma Park',
       'San Francisco, CA - Midtown Terrace',
       'San Francisco, CA - Marina Gardens',
       'San Francisco, CA - Marina District',
       'San Francisco, CA - Lower Pacific Heights',
       'San Francisco, CA - Lower Nob Hill',
       'San Francisco, CA - Lower Haight',
       'San Francisco, CA - Lone Mountain',
       'San Francisco, CA - Laurel Heights-Jordan Park',
       'San Francisco, CA - Lakeshore Acres',
       'San Francisco, CA - Lake Street',
       'San Francisco, CA - Laguna Honda',
       'San Francisco, CA - Inner Sunset',
       'San Francisco, CA - Inner Richmond',
       'San Francisco, CA - Ingleside', 'San Francisco, CA - Holly Park',
       'San Francisco, CA - Hayes Valley',
       'San Francisco, CA - Haight Ashbury',
       'San Francisco, CA - Golden Gate Heights',
       'San Francisco, CA - Glen Park', 'San Francisco, CA - Forest Hill',
       'San Francisco, CA - Fairmount', 'San Francisco, CA - Excelsior',
       'San Francisco, CA - Eureka Valley',
       'San Francisco, CA - Duboce Triangle',
       'San Francisco, CA - Dolores Heights',
       'San Francisco, CA - Diamond Heights',
       'San Francisco, CA - Crocker Amazon',
       'San Francisco, CA - Cow Hollow',
       'San Francisco, CA - Corona Heights',
       'San Francisco, CA - Clarendon Heights',
       'San Francisco, CA - Central South of Market',
       'San Francisco, CA - Cayuga', 'San Francisco, CA - Cathedral Hill',
       'San Francisco, CA - Castro',
       'San Francisco, CA - Candlestick Point State Recreation Area',
       'San Francisco, CA - Buena Vista',
       'San Francisco, CA - Bret Harte',
       'San Francisco, CA - Bernal Heights',
       'San Francisco, CA - Bayview', 'San Francisco, CA - Balboa Hollow',
       'San Francisco, CA - Ashbury Heights / Parnassus',
       'San Francisco, CA - Ashbury Heights'], dtype=object)

In [5]:
police_reports = pd.read_csv('Police_Department_Incident_Reports__2018_to_Present.csv')

In [6]:
police_reports.head()

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,SF Find Neighborhoods,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods,HSOC Zones as of 2018-06-05,OWED Public Spaces,Central Market/Tenderloin Boundary Polygon - Updated,Parks Alliance CPSI (27+TL sites),ESNCAG - Boundary File,"Areas of Vulnerability, 2016"
0,2020/02/03 02:45:00 PM,2020/02/03,14:45,2020,Monday,2020/02/03 05:50:00 PM,89881675000,898816,200085557,200342870.0,...,41.0,10.0,8.0,16.0,NaN,NaN,NaN,NaN,NaN,2.0
1,2020/02/03 03:45:00 AM,2020/02/03,03:45,2020,Monday,2020/02/03 03:45:00 AM,89860711012,898607,200083749,200340316.0,...,53.0,3.0,2.0,20.0,3.0,NaN,NaN,NaN,NaN,2.0
2,2020/02/03 10:00:00 AM,2020/02/03,10:00,2020,Monday,2020/02/03 10:06:00 AM,89867264015,898672,200084060,200340808.0,...,19.0,5.0,3.0,8.0,NaN,35.0,NaN,NaN,NaN,2.0
3,2020/01/19 05:12:00 PM,2020/01/19,17:12,2020,Sunday,2020/02/01 01:01:00 PM,89863571000,898635,206024187,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020/01/05 12:00:00 AM,2020/01/05,00:00,2020,Sunday,2020/02/03 04:09:00 PM,89877368020,898773,200085193,200342341.0,...,103.0,4.0,6.0,30.0,NaN,NaN,NaN,NaN,NaN,1.0

In [7]:
police_reports1 = police_reports.loc[: , ['Incident Date', 'Incident Category', 'Police District', 'Analysis Neighborhood']]

In [8]:
police_reports1.head()

,Incident Date,Incident Category,Police District,Analysis Neighborhood
0,2020/02/03,Missing Person,Taraval,Lakeshore
1,2020/02/03,Stolen Property,Mission,Mission
2,2020/02/03,Non-Criminal,Tenderloin,Financial District/South Beach
3,2020/01/19,Lost Property,Taraval,NaN
4,2020/01/05,Miscellaneous Investigation,Richmond,Pacific Heights

In [9]:
police_reports1['Police District'].unique()

array(['Taraval', 'Mission', 'Tenderloin', 'Richmond', 'Central',
       'Out of SF', 'Southern', 'Park', 'Bayview', 'Northern',
       'Ingleside'], dtype=object)

In [10]:
police_reports1['Analysis Neighborhood'].unique()

array(['Lakeshore', 'Mission', 'Financial District/South Beach', nan,
       'Pacific Heights', 'Castro/Upper Market', 'Twin Peaks',
       'Bayview Hunters Point', 'Sunset/Parkside', 'Western Addition',
       'South of Market', 'Golden Gate Park', 'Mission Bay',
       'North Beach', 'Potrero Hill', 'Russian Hill', 'Outer Mission',
       'Haight Ashbury', 'Tenderloin', 'Hayes Valley', 'Japantown',
       'Nob Hill', 'Chinatown', 'West of Twin Peaks', 'Lone Mountain/USF',
       'Outer Richmond', 'Noe Valley', 'Excelsior', 'Portola',
       'Inner Richmond', 'Bernal Heights', 'Glen Park', 'Marina',
       'Treasure Island', 'Presidio Heights', 'Inner Sunset',
       'Visitacion Valley', 'Oceanview/Merced/Ingleside', 'Lincoln Park',
       'Presidio', 'McLaren Park', 'Seacliff'], dtype=object)

In [11]:
len(police_reports1['Analysis Neighborhood'].unique())

42

In [12]:
len(median_prices.Region.unique())

84

In [13]:
median_prices.loc[5, 'Region'].replace('San Francisco, CA - ', "")

'Western South of Market'

In [14]:
median_prices1 = median_prices

In [17]:
median_prices1['Region'] = [median_prices.loc[i,'Region'].replace('San Francisco, CA - ', "")
                            .replace('') for i in range(len(median_prices))]

In [18]:
median_prices1.head()

,Month of Period End,Region,Avg. Median Sale Price,Avg. Median Ppsf
0,Feb-12,Western South of Market,$522K,514.7540984
1,Mar-12,Western South of Market,$519K,496.0554931
2,Apr-12,Western South of Market,$530K,508.4507042
3,May-12,Western South of Market,$540K,530.2325581
4,Jun-12,Western South of Market,$590K,532.2981146

In [20]:
median_prices1['Region'].unique()

array(['Western South of Market', 'Western Addition', 'West Portal',
       'Visitacion Valley', 'Upper Market', 'University Mound',
       'Union Street', 'Tenderloin', 'Telegraph Hill', 'Sutro Heights',
       'Sunnyside', 'St. Marys Park', 'Southwest San Francisco',
       'Southeast San Francisco', 'South of Market', 'South Beach',
       'Silver Terrace', 'Russian Hill', 'Rincon Hill',
       'Presidio Terrace', 'Presidio Heights', 'Potrero Hill', 'Portola',
       'Polk Gulch', 'Peralta Heights', 'Parkside', 'Panhandle',
       'Pacific Heights', 'Outer Sunset', 'Outer Richmond',
       'Outer Mission', 'Oceanview', 'Northwest San Francisco',
       'Northeast San Francisco', 'North Beach', 'Noe Valley', 'Nob Hill',
       'Mission Terrace', 'Mission Dolores', 'Mission District',
       'Mission Bay', 'Miraloma Park', 'Midtown Terrace',
       'Marina Gardens', 'Marina District', 'Lower Pacific Heights',
       'Lower Nob Hill', 'Lower Haight', 'Lone Mountain',
       'Laurel Heights-Jordan Park', 'Lakeshore Acres', 'Lake Street',
       'Laguna Honda', 'Inner Sunset', 'Inner Richmond', 'Ingleside',
       'Holly Park', 'Hayes Valley', 'Haight Ashbury',
       'Golden Gate Heights', 'Glen Park', 'Forest Hill', 'Fairmount',
       'Excelsior', 'Eureka Valley', 'Duboce Triangle', 'Dolores Heights',
       'Diamond Heights', 'Crocker Amazon', 'Cow Hollow',
       'Corona Heights', 'Clarendon Heights', 'Central South of Market',
       'Cayuga', 'Cathedral Hill', 'Castro',
       'Candlestick Point State Recreation Area', 'Buena Vista',
       'Bret Harte', 'Bernal Heights', 'Bayview', 'Balboa Hollow',
       'Ashbury Heights / Parnassus', 'Ashbury Heights'], dtype=object)

In [29]:
population_sf = 883305

In [33]:
police_reports_count = police_reports1.groupby('Analysis Neighborhood').count().drop(['Incident Date', 'Incident Category'], axis=1)

In [36]:
police_reports_count.head()

                       Police District
Analysis Neighborhood
Bayview Hunters Point            18555
Bernal Heights                    5554
Castro/Upper Market               9663
Chinatown                         6412
Excelsior                         5047

In [39]:
police_reports_count['Crime Rate'] = police_reports_count['Police District'] / population_sf

In [40]:
police_reports_count.rename(columns={"Police District": "Total Crimes"})

                                Total Crimes  Crime Rate
Analysis Neighborhood
Bayview Hunters Point                  18555    0.021006
Bernal Heights                          5554    0.006288
Castro/Upper Market                     9663    0.010940
Chinatown                               6412    0.007259
Excelsior                               5047    0.005714
Financial District/South Beach         29813    0.033752
Glen Park                               1593    0.001803
Golden Gate Park                        3472    0.003931
Haight Ashbury                          5369    0.006078
Hayes Valley                            8709    0.009860
Inner Richmond                          4200    0.004755
Inner Sunset                            3789    0.004290
Japantown                               3434    0.003888
Lakeshore                               3829    0.004335
Lincoln Park                             404    0.000457
Lone Mountain/USF                       3883    0.004396
Marina                                  7669    0.008682
McLaren Park                             315    0.000357
Mission                                36851    0.041719
Mission Bay                             5442    0.006161
Nob Hill                                9209    0.010426
Noe Valley                              2958    0.003349
North Beach                            10130    0.011468
Oceanview/Merced/Ingleside              3250    0.003679
Outer Mission                           4336    0.004909
Outer Richmond                          7007    0.007933
Pacific Heights                         5276    0.005973
Portola                                 3510    0.003974
Potrero Hill                            5082    0.005753
Presidio                                 764    0.000865
Presidio Heights                        1849    0.002093
Russian Hill                            7279    0.008241
Seacliff                                 355    0.000402
South of Market                        27781    0.031451
Sunset/Parkside                         9256    0.010479
Tenderloin                             33106    0.037480
Treasure Island                         1016    0.001150
Twin Peaks                              1628    0.001843
Visitacion Valley                       3537    0.004004
West of Twin Peaks                      6363    0.007204
Western Addition                       10558    0.011953

In [41]:
police_reports_count.head()

                       Police District  Crime Rate
Analysis Neighborhood
Bayview Hunters Point            18555    0.021006
Bernal Heights                    5554    0.006288
Castro/Upper Market               9663    0.010940
Chinatown                         6412    0.007259
Excelsior                         5047    0.005714